### ISSUE TITLE
Fix crash

### ISSUE THREAD

**Issue by lindolsang** [lindolsang/My-Cashbook#20]
Replication log

```
6158-6158  AndroidRuntime          kr.lindol.mycashbook                 E  FATAL EXCEPTION: main
                                                                                                    Process: kr.lindol.mycashbook, PID: 6158
                                                                                                    java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
                                                                                                    	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                                                                                                    	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                                                                                                    	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                                                                                                    	at java.util.Objects.checkIndex(Objects.java:359)
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:434)
                                                                                                    	at kr.lindol.mycashbook.list.CashLogListFragment$CashLogListAdapter.getItem(CashLogListFragment.java:634)
                                                                                                    	at kr.lindol.mycashbook.list.CashLogListFragment.hideMemo(CashLogListFragment.java:346)
                                                                                                    	at kr.lindol.mycashbook.list.CashLogListPresenter.selectCashLog(CashLogListPresenter.java:279)
                                                                                                    	at kr.lindol.mycashbook.list.CashLogListFragment$4.onItemClick(CashLogListFragment.java:173)
                                                                                                    	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
                                                                                                    	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
                                                                                                    	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
                                                                                                    	at android.widget.AbsListView$3.run(AbsListView.java:4244)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
2023-12-18 00:15:21.689  6158-6158  Process                 kr.lindol.mycashbook                 I  Sending signal. PID: 6158 SIG: 9

```

Replication path:
Show memo (at 3) -> navigate other date -> show memo (at 1 or 2)

**Comment by lindolsang** [comment]
This was fixed by 1571470a0a654254824af2a1c094d21e66393263 commit
